# .sops.yaml
keys:
  - &dev1 age1ty9te3e0hee5u2vempp9x4h8cxhx0eppu84rgyvfsp0hhvmwwpzqlj2zvk

creation_rules:
  - path_regex: '(?i)^certs[\/\\][^\/\\]+[\/\\]tls\.key\.enc$'
    age:
      - *dev1
    encrypted_regex: '^(data|binary)$'
